# 使用字体的文件路径
font_file: resources/allseto.ttf

# 文本换行算法，可选值："original"(原始算法), "knuth_plass"(改进的Knuth-Plass算法)
text_wrap_algorithm: "original"

# 将差分表情导入，默认底图base.png
baseimage_mapping:
  "普通": "resources/BaseImages/base.png"
  "开心": "resources/BaseImages/开心.png"
  "生气": "resources/BaseImages/生气.png"
  "无语": "resources/BaseImages/无语.png"
  "脸红": "resources/BaseImages/脸红.png"
  "病娇": "resources/BaseImages/病娇.png"
  "闭眼": "resources/BaseImages/闭眼.png"
  "难受": "resources/BaseImages/难受.png"
  "害怕": "resources/BaseImages/害怕.png"
  "激动": "resources/BaseImages/激动.png"
  "惊讶": "resources/BaseImages/惊讶.png"
  "哭泣": "resources/BaseImages/哭泣.png"

# 默认底图文件路径
baseimage_file: resources/BaseImages/base.png

# 文本框左上角坐标 (x, y), 同时适用于图片框
text_box_topleft: [119, 450]
# 文本框右下角坐标 (x, y), 同时适用于图片框
image_box_bottomright: [398, 625]

# 置顶图层的文件路径
base_overlay_file: resources/BaseImages/base_overlay.png
# 是否启用底图的置顶图层, 用于表现遮挡
use_base_overlay: true

# 日志记录等级, 可选值有 "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
logging_level: INFO

# 是否将Bot的所有文本消息替换为安安的素描本（WARN：这是一个可能存在诸多Bug的实验性功能，开启该功能有损坏消息发送逻辑的风险，请谨慎启用）
convert_all_to_anan: false
#如果Bot的消息的长度大于这个值，原样发送消息（避免因字体过小无法看清）
max_len_of_long_text: 150