# 字体文件路径
font_file: sources/allseto.ttf

# 底图映射表，可自定义表情底图
baseimage_mapping:
  "普通": "sources/BaseImages/base.png"
  "开心": "sources/BaseImages/开心.png"
  "生气": "sources/BaseImages/生气.png"
  "无语": "sources/BaseImages/无语.png"
  "脸红": "sources/BaseImages/脸红.png"
  "病娇": "sources/BaseImages/病娇.png"

# 默认底图文件路径
baseimage_file: sources/BaseImages/base.png

# 文本框坐标（左上角、右下角）
text_box_topleft: [119, 450]
image_box_bottomright: [398, 625]

# 置顶图层设置
base_overlay_file: sources/BaseImages/base_overlay.png
use_base_overlay: true

# 日志等级
logging_level: INFO
