# 使用字体的文件路径
font_file: sources/allseto.ttf

# 将差分表情导入，默认底图base.png
baseimage_mapping:
  "普通": "sources/BaseImages/base.png"
  "开心": "sources/BaseImages/开心.png"
  "生气": "sources/BaseImages/生气.png"
  "无语": "sources/BaseImages/无语.png"
  "脸红": "sources/BaseImages/脸红.png"
  "病娇": "sources/BaseImages/病娇.png"

# 默认底图文件路径
baseimage_file: sources/BaseImages/base.png

# 文本框左上角坐标 (x, y), 同时适用于图片框
text_box_topleft: [119, 450]
# 文本框右下角坐标 (x, y), 同时适用于图片框
image_box_bottomright: [398, 625]

# 置顶图层的文件路径
base_overlay_file: sources/BaseImages/base_overlay.png
# 是否启用底图的置顶图层, 用于表现遮挡
use_base_overlay: true

# 日志记录等级, 可选值有 "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
logging_level: INFO
